title = "1Digital gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Global allowlist"
paths = [
  '''.gitleaks\.toml''',
  '''pnpm-lock\.yaml''',
  '''package-lock\.json''',
  '''\.env\.example''',
]
